### ISSUE TITLE
Create: forgotpassword.html

### ISSUE THREAD

**Issue by tomscholz** [tomscholz/materialize-map-template#13]
Try to use a similar design as these two:
* map.scholzworks.de/login.html
* map.scholzworks.de/register.html

On the right should be the same content as on the register.html
The left side should look like this, but in material design: 
![bildschirmfoto 2016-10-22 um 20 41 02](https://cloud.githubusercontent.com/assets/20381749/19621708/04d3c4a4-9898-11e6-8c6d-e37adcc16e01.png)

**Comment by BhaveshSGupta** [comment]
I can take this one
